"""Beya SDK - Python client for the Beya Gateway API."""

__version__ = "0.1.0"

from .client import AsyncBeyaClient, BeyaClient
from .models import (
    AgentInfo,
    ApprovalRequest,
    DiagnosticEvent,
    Event,
    EventType,
    McpServerInfo,
    ModelInfo,
    OpenAIChatCompletion,
    OpenAIChatCompletionChunk,
    OpenAIChatMessage,
    PluginDetail,
    ProviderInfo,
    ReviewState,
    RunEvent,
    Schedule,
    Session,
    SessionSummary,
    SkillDetail,
    TaskHandle,
    TaskStatus,
    TaskStatusEnum,
    TeamInfo,
    ToolDetail,
    WorkspaceFile,
)
from .errors import (
    AuthenticationError,
    BeyaError,
    GatewayUnavailableError,
    LocalExecutionError,
    PermissionDeniedError,
    ProviderError,
    RateLimitError,
    SessionNotFoundError,
    ServerError,
    TaskNotFoundError,
    ValidationError,
)

__all__ = [
    "BeyaClient",
    "AsyncBeyaClient",
    "AgentInfo",
    "ApprovalRequest",
    "DiagnosticEvent",
    "Event",
    "EventType",
    "McpServerInfo",
    "ModelInfo",
    "OpenAIChatCompletion",
    "OpenAIChatCompletionChunk",
    "OpenAIChatMessage",
    "PluginDetail",
    "ProviderInfo",
    "ReviewState",
    "RunEvent",
    "Schedule",
    "Session",
    "SessionSummary",
    "SkillDetail",
    "TaskHandle",
    "TaskStatus",
    "TaskStatusEnum",
    "TeamInfo",
    "ToolDetail",
    "WorkspaceFile",
    "AuthenticationError",
    "BeyaError",
    "GatewayUnavailableError",
    "LocalExecutionError",
    "PermissionDeniedError",
    "ProviderError",
    "RateLimitError",
    "SessionNotFoundError",
    "ServerError",
    "TaskNotFoundError",
    "ValidationError",
]
