"""Beya SDK - Python client for the Beya Server API."""

__version__ = "0.1.0"

from .client import AsyncBeyaClient, BeyaClient
from .plugins import (
    ConnectorToolExecutor,
    RemoteToolExecutor,
    SdkPluginDefinition,
    SdkSkillDefinition,
    SdkToolDefinition,
    define_plugin,
    define_skill,
    define_tool,
)
from .models import (
    AgentInfo,
    ApprovalRequest,
    ChatResult,
    DiagnosticEvent,
    Event,
    McpServerInfo,
    ModelInfo,
    PluginDetail,
    ProviderInfo,
    ReviewState,
    RunEvent,
    Schedule,
    Session,
    SessionSummary,
    SkillDetail,
    TaskListItem,
    TeamInfo,
    ToolDetail,
    WorkspaceFile,
)
from .errors import (
    AuthenticationError,
    BeyaError,
    BeyaServerUnavailableError,
    LocalExecutionError,
    PermissionDeniedError,
    ProviderError,
    RateLimitError,
    SessionNotFoundError,
    ServerError,
    TaskNotFoundError,
    ValidationError,
)

__all__ = [
    "BeyaClient",
    "AsyncBeyaClient",
    "ConnectorToolExecutor",
    "RemoteToolExecutor",
    "SdkPluginDefinition",
    "SdkSkillDefinition",
    "SdkToolDefinition",
    "define_plugin",
    "define_skill",
    "define_tool",
    "AgentInfo",
    "ApprovalRequest",
    "ChatResult",
    "DiagnosticEvent",
    "Event",
    "McpServerInfo",
    "ModelInfo",
    "PluginDetail",
    "ProviderInfo",
    "ReviewState",
    "RunEvent",
    "Schedule",
    "Session",
    "SessionSummary",
    "SkillDetail",
    "TaskListItem",
    "TeamInfo",
    "ToolDetail",
    "WorkspaceFile",
    "AuthenticationError",
    "BeyaError",
    "BeyaServerUnavailableError",
    "LocalExecutionError",
    "PermissionDeniedError",
    "ProviderError",
    "RateLimitError",
    "SessionNotFoundError",
    "ServerError",
    "TaskNotFoundError",
    "ValidationError",
]
